version: "3.0"
services:
  db:
    image: mysql:latest
    env_file: ./.env
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    volumes:
      - datafiles:/var/lib/mysql
    restart: always
    healthcheck:
      test: "mysql $MYSQL_DATABASE -u$MYSQL_USER -p$MYSQL_PASSWORD -e 'SELECT 1;'"
      interval: 30s
      timeout: 10s
      retries: 10
      
  api:
    depends_on:
      db:
        condition: service_healthy
      mq:
        condition: service_healthy
    build: ./api/ShopAholytics
    env_file: ./.env
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://db:$MYSQL_DOCKER_PORT/$MYSQL_DATABASE?useSSL=true",
        "spring.datasource.username" : "$MYSQL_USER",
        "spring.datasource.password" : "$MYSQL_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL8Dialect",
        "spring.jpa.hibernate.ddl-auto" : "update",
        "spring.rabbitmq.host" : "mq",
        "spring.rabbitmq.port" : $RMQ_AMQP_DOCKER_PORT,
        "spring.rabbitmq.username" : "$RMQ_USER",
        "spring.rabbitmq.password": "$RMQ_PASSWORD",
        "server.port": $SPRING_DOCKER_PORT
      }'
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    restart: on-failure
    healthcheck:
      test: "curl http://localhost:$SPRING_DOCKER_PORT/"
      interval: 30s
      timeout: 10s
      retries: 10
      
  client:
    depends_on:
      api: 
        condition: service_healthy
    build: ./FrontEnd
    env_file: ./.env
    environment:
      API_URL: "localhost:$SPRING_DOCKER_PORT"
    ports:
      - $CLIENT_LOCAL_PORT:$CLIENT_DOCKER_PORT
    volumes:
      - ./FrontEnd:/usr/share/nginx/html
    healthcheck:
      test: "curl http://localhost:$CLIENT_DOCKER_PORT/"
      interval: 30s
      timeout: 10s
      retries: 10

  mq:
    image: rabbitmq:management
    ports:
      - $RMQ_HTTP_LOCAL_PORT:$RMQ_HTTP_DOCKER_PORT
      - $RMQ_AMQP_LOCAL_PORT:$RMQ_AMQP_DOCKER_PORT
    healthcheck:
      test: "rabbitmq-diagnostics -q status"
      interval: 30s
      timeout: 10s
      retries: 10

volumes:
  datafiles:
       

