version: "3.0"
services:
  db:
    image: mysql:latest
    env_file: ./.env
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    volumes:
      - datafiles:/var/lib/mysql
    restart: always
      
  api:
    depends_on:
      - db
    build: ./api/ShopAholytics
    env_file: ./.env
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://db:$MYSQL_DOCKER_PORT/$MYSQL_DATABASE?useSSL=true",
        "spring.datasource.username" : "$MYSQL_USER",
        "spring.datasource.password" : "$MYSQL_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL8Dialect",
        "spring.jpa.hibernate.ddl-auto" : "update",
        "server.port": $SPRING_DOCKER_PORT
      }'
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    restart: on-failure
      
volumes:
  datafiles:
       

