version: "3.1"
services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ies_52
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - datafiles:/var/lib/mysql
      - ../db/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    ports:
      - 3300:3300
    restart: always

volumes:
  datafiles: